name: Publish Binaries to Release (Windows)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Values
        run: |
          VERSION="$(git describe --tags --abbrev=0)"
          BUILD_DATE="$(date -u '+%d %b %Y')"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "BUILD_DATE=${BUILD_DATE}" >> $GITHUB_ENV
          echo "LDFLAGS=$(make print-ldflags VERSION=${VERSION} BUILD_DATE=\"${BUILD_DATE}\")" >> $GITHUB_ENV

      - name: Build
        uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "."
          binary_name: "bloodhound-cli"
          ldflags: ${{ env.LDFLAGS }}
          release_tag: ${{ github.ref_name }}
          overwrite: true
          executable_compression: upx --brute
          asset_name: bloodhound-cli-${{ matrix.goos }}-${{ matrix.goarch }}
